## 1 - Validação e Tratamento de Dados Ausentes

#### 1.1) - Fiz uma cópia do .csv na pasta ‘C:\Dev\sctec\sctec_mini-projeto_avaliativo’
#### 1.2) - Ler `halloween_vendas.csv` com `pd.read_csv()`, da biblioteca Pandas.

In [54]:
import pandas as pd

df = pd.read_csv("halloween_vendas.csv")

df

,pedido_id,data_venda,produto,categoria,canal_venda,cidade,quantidade,preco_unitario,custo_unitario,desconto_pct,status_pedido,publico,tamanho,data_entrega
0,844,2025-11-21 18:02:35,Fantasia de vampiro,Fantasia,Loja física,Curitiba,3,132.50,72.08,15,Cancelado,Adulto,G,NaN
1,378,2024-10-29 18:41:26,Fantasia de bruxa,FANTASIA!!!,Loja física,Maringá,3,110.00,57.00,5,Concluído,Adulto,M,2024-11-03 18:41:26
2,953,2025-09-05 21:16:09,Fantasia de bruxa,Fantasia,Web,Maringá,2,116.60,60.42,5,Concluído,Adulto,M,2025-09-10 21:16:09
3,11,2024-11-08 11:29:44,Mascara assustadora,Acessorio,Loja física,Cascavel,1,35.00,12.00,15,Concluído,Todos,Unico,2024-11-11 11:29:44
4,1335,2025-08-23 11:22:05,Mascara assustadora,Acessorio,Mercado,Curitiba,3,37.10,12.72,0,Concluído,Todos,Unico,2025-08-25 11:22:05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,660,2024-11-09 09:13:34,Mascara assustadora,Acessorio,loja física,Maringá,2,35.00,12.00,0,Concluído,Todos,Unico,2024-11-11 09:13:34
1496,772,2025-10-21 15:40:35,Fantasia de bruxa,Fantasia,Loja física,Maringá,1,116.60,60.42,5,Concluído,Adulto,M,2025-10-25 15:40:35
1497,25,2024-09-22 19:03:42,Chapeu de bruxa,Acessorio,Web,Maringá,3,22.00,8.00,5,Concluído,Todos,Unico,2024-09-24 19:03:42
1498,1147,2025-10-22 16:00:11,Chapeu de bruxa,Acessorio,Mercado,Cascavel,5,23.32,8.48,0,Concluído,Todos,Unico,2025-10-26 16:00:11
1499,271,2024-09-11 14:55:09,Chapeu de bruxa,Acessorio,Mercado,Londrina,2,22.00,8.00,0,Concluído,Todos,Unico,2024-09-14 14:55:09

#### 1.3) - Confira as linhas, os nomes das colunas e o total de registros.

In [56]:
# len(df) conta as linhas, e df.columns.tolist() mostra os nomes das colunas. 
# Confere se elas se chamam exatamente categoria, quantidade e preco_unitario.

print("Total de linhas:", len(df))
print("Nomes das colunas:", df.columns.tolist())
display(df.head())

Total de linhas: 1500
Nomes das colunas: ['pedido_id', 'data_venda', 'produto', 'categoria', 'canal_venda', 'cidade', 'quantidade', 'preco_unitario', 'custo_unitario', 'desconto_pct', 'status_pedido', 'publico', 'tamanho', 'data_entrega']

,pedido_id,data_venda,produto,categoria,canal_venda,cidade,quantidade,preco_unitario,custo_unitario,desconto_pct,status_pedido,publico,tamanho,data_entrega
0,844,2025-11-21 18:02:35,Fantasia de vampiro,Fantasia,Loja física,Curitiba,3,132.5,72.08,15,Cancelado,Adulto,G,NaN
1,378,2024-10-29 18:41:26,Fantasia de bruxa,FANTASIA!!!,Loja física,Maringá,3,110.0,57.00,5,Concluído,Adulto,M,2024-11-03 18:41:26
2,953,2025-09-05 21:16:09,Fantasia de bruxa,Fantasia,Web,Maringá,2,116.6,60.42,5,Concluído,Adulto,M,2025-09-10 21:16:09
3,11,2024-11-08 11:29:44,Mascara assustadora,Acessorio,Loja física,Cascavel,1,35.0,12.00,15,Concluído,Todos,Unico,2024-11-11 11:29:44
4,1335,2025-08-23 11:22:05,Mascara assustadora,Acessorio,Mercado,Curitiba,3,37.1,12.72,0,Concluído,Todos,Unico,2025-08-25 11:22:05

### 1.4) - Preencher categorias vazias com a string "sem categoria".

In [58]:
# Conta categorias vazias antes de preenchê-las
categoria_texto = df["categoria"].astype("string").str.strip()
categorias_vazias = categoria_texto.isna() | categoria_texto.eq("").fillna(False)
categorias_vazias_preenchidas = int(categorias_vazias.sum())


print("Categorias vazias:", categorias_vazias_preenchidas)


# Preenche sem alterar as demais categorias
df["categoria"] = categoria_texto.mask(categorias_vazias, "sem categoria")

Categorias vazias: 0

### 1.5) - Verificar se quantidade é inteira e maior que zero
### 1.6) - Verificar se preco_unitario está preenchido e não é negativo
### 1.7) - Marcar os registros com problemas

In [60]:
# Seleciona somente os pedidos com problema numérico.
pedidos_com_problema = df.loc[df["tem_problema_numerico"]]

# Mostra quantos pedidos foram encontrados.
print("Total de pedidos com problemas:", len(pedidos_com_problema))

# Exibe os dados que ajudam a identificar o problema em cada pedido.
display(
    pedidos_com_problema[
        [
            "pedido_id",
            "quantidade",
            "preco_unitario",
            "problema_quantidade",
            "problema_preco_unitario",
        ]
    ]
)

Total de pedidos com problemas: 19

,pedido_id,quantidade,preco_unitario,problema_quantidade,problema_preco_unitario
23,1500,3,NaN,False,True
164,630,-1,22.00,True,False
199,625,2,NaN,False,True
216,1000,1,NaN,False,True
239,1250,1,NaN,False,True
293,500,1,NaN,False,True
503,375,3,NaN,False,True
571,250,4,NaN,False,True
583,125,1,NaN,False,True
672,840,-1,23.32,True,False
845,420,-1,35.00,True,False
1066,875,6,NaN,False,True
1092,750,2,NaN,False,True
1126,210,-1,125.00,True,False
1260,1050,-1,90.10,True,False
1275,1375,2,NaN,False,True
1312,1125,1,NaN,False,True
1448,1260,-1,23.32,True,False
1481,1470,-1,132.50,True,False

### 1.8) - Justificar regra nos comentários e no README.

Categorias vazias ou preenchidas apenas com espaços foram substituídas por “sem categoria”. A quantidade foi considerada válida quando podia ser interpretada como número inteiro maior que zero. O preço unitário foi considerado válido quando estava preenchido, podia ser interpretado como número e era maior ou igual a zero. Registros problemáticos foram marcados, sem inventar ou substituir valores.

### 1.9) - Conte os problemas por campo.

In [63]:
# Conta quantos registros têm problema na quantidade.
problemas_quantidade = int(df["problema_quantidade"].sum())

# Conta quantos registros têm problema no preço unitário.
problemas_preco = int(df["problema_preco_unitario"].sum())

# Exibe a quantidade de problemas encontrados em cada campo.
print("Problemas no campo quantidade:", problemas_quantidade)
print("Problemas no campo preco_unitario:", problemas_preco)

Problemas no campo quantidade: 7
Problemas no campo preco_unitario: 12

### 1.10) - Total de pedidos afetados por estes problemas e evitar sobreposição.

In [ ]:
# Marca os pedidos com problema na quantidade ou no preço unitário.
# O operador | significa "ou".

pedido_com_problema = (
    df["problema_quantidade"] | df["problema_preco_unitario"]
)

# Seleciona os pedidos marcados, sem contar duas vezes os que têm ambos os problemas.
pedidos_afetados = df.loc[pedido_com_problema]

# Exibe o total de pedidos afetados.
print("Total de pedidos afetados:", len(pedidos_afetados))

# Mostra os identificadores e as marcações para conferência.
display(
    pedidos_afetados[
        [
            "pedido_id",
            "problema_quantidade",
            "problema_preco_unitario",
        ]
    ]
)

Total de pedidos afetados: 19

      pedido_id  problema_quantidade  problema_preco_unitario
23         1500                False                     True
164         630                 True                    False
199         625                False                     True
216        1000                False                     True
239        1250                False                     True
293         500                False                     True
503         375                False                     True
571         250                False                     True
583         125                False                     True
672         840                 True                    False
845         420                 True                    False
1066        875                False                     True
1092        750                False                     True
1126        210                 True                    False
1260       1050                 True                    False
1275       1375                False                     True
1312       1125                False                     True
1448       1260                 True                    False
1481       1470                 True                    False

## 2 - Padronização de Strings e Regex

   ### 2.1) - Retirar a pontuação indevida com .strip(), .lower() e re.sub()

In [65]:
import re

# Guarda os valores originais para preservar a referência antes da limpeza.
categoria_original = df["categoria"].astype("string")

# Remove espaços das pontas e converte as letras para minúsculas.
categoria_limpa = categoria_original.str.strip().str.lower()

# Troca valores ausentes por texto vazio para a limpeza não falhar.
categoria_limpa = categoria_limpa.fillna("")

# Remove tudo que não seja letra sem acento (a-z) ou espaço.
# A expressão regular preserva os espaços entre palavras.
categoria_limpa = categoria_limpa.map(
    lambda texto: re.sub(r"[^a-z\s]", "", texto).strip()
)

# Salva o resultado limpo na coluna categoria.
df["categoria"] = categoria_limpa

   ### 2.2) - Preencher ausências com ‘sem categoria’.

In [68]:
# Guarda quais linhas estavam vazias após a limpeza do item 2.1.
categorias_vazias_apos_limpeza = (
    df["categoria"].isna()
    | df["categoria"].astype("string").str.strip().eq("").fillna(False)
)

# Preenche essas categorias com "sem categoria".
df.loc[categorias_vazias_apos_limpeza, "categoria"] = "sem categoria"

# Conta quantas categorias foram preenchidas.
total_preenchidas = int(categorias_vazias_apos_limpeza.sum())
print("Categorias preenchidas:", total_preenchidas)

# Mostra o pedido, o valor original e o valor preenchido.
resultado_preenchimento = df.loc[
    categorias_vazias_apos_limpeza, ["pedido_id"]
].copy()

resultado_preenchimento["categoria original"] = categoria_original.loc[
    categorias_vazias_apos_limpeza
]
resultado_preenchimento["categoria após preenchimento"] = df.loc[
    categorias_vazias_apos_limpeza, "categoria"
]

display(resultado_preenchimento)

Categorias preenchidas: 0

Empty DataFrame
Columns: [pedido_id, categoria original, categoria após preenchimento]
Index: []

### 2.3) - Contabilista categorias vazias que foram preenchidas e as não vazias alteradas separadamente.

In [69]:
# Marca as categorias que já estavam vazias no texto original.
categoria_original_texto = categoria_original.astype("string")
vazias_no_original = (
    categoria_original_texto.isna()
    | categoria_original_texto.str.strip().eq("").fillna(False)
)

# Conta as categorias vazias que foram preenchidas no item 2.2.
total_vazias_preenchidas = int(vazias_no_original.sum())

# Compara o resultado final com o original e conta mudanças
# somente nas categorias que originalmente não estavam vazias.
nao_vazias_alteradas = (
    ~vazias_no_original
    & df["categoria"].astype("string").ne(categoria_original_texto)
)
total_nao_vazias_alteradas = int(nao_vazias_alteradas.sum())

# Exibe as duas contagens separadamente.
print("Categorias vazias preenchidas:", total_vazias_preenchidas)
print("Categorias não vazias alteradas:", total_nao_vazias_alteradas)

Categorias vazias preenchidas: 0
Categorias não vazias alteradas: 1482

### 2.4) - Padronizar canal de venda para Mercado, Loja Física e Web.

In [71]:
# Guarda os valores originais para poder compará-los depois, se necessário.
canal_original = df["canal_venda"].copy()

# Remove espaços das pontas e converte o texto para minúsculas.
canal_normalizado = (
    df["canal_venda"]
    .astype("string")
    .str.strip()
    .str.lower()
)

# Define o nome padronizado correspondente a cada canal.
mapa_canais = {
    "mercado": "Mercado",
    "loja física": "Loja física",
    "web": "Web",
}

# Substitui cada valor normalizado pelo nome padronizado.
canal_padronizado = canal_normalizado.map(mapa_canais)

# Interrompe com uma mensagem clara se houver canal inesperado ou ausente.
if canal_padronizado.isna().any():
    canais_invalidos = (
        canal_normalizado[canal_padronizado.isna()]
        .fillna("<ausente>")
        .unique()
        .tolist()
    )
    raise ValueError(f"Canais sem padronização: {canais_invalidos}")

# Atualiza a coluna com os canais padronizados.
df["canal_venda"] = canal_padronizado

# Exibe a contagem final de pedidos por canal.
print("Pedidos por canal padronizado:")
display(df["canal_venda"].value_counts())

Pedidos por canal padronizado:

canal_venda
Web            666
Loja física    551
Mercado        283
Name: count, dtype: int64

# 3 - Lógica de Regra de Negócio (Filtros e Validação)

### 3.1) - Verificar de pedido com data vazia foi cancelado.

In [73]:
# Converte a coluna de data para texto e remove espaços das pontas.
data_entrega_texto = df["data_entrega"].astype("string").str.strip()

# Marca como vazias as datas ausentes ou que contêm apenas espaços.
data_vazia = (
    df["data_entrega"].isna()
    | data_entrega_texto.eq("").fillna(False)
)

# Prepara os status para comparar sem diferença de espaços ou maiúsculas.
status_normalizado = (
    df["status_pedido"]
    .astype("string")
    .str.strip()
    .str.casefold()
)

# Marca como True os pedidos cujo status é "Cancelado".
status_cancelado = status_normalizado.eq("cancelado").fillna(False)

# Seleciona os pedidos sem data e cria uma cópia para a análise.
pedidos_sem_entrega = df.loc[data_vazia].copy()

# Adiciona uma coluna indicando se cada pedido foi cancelado.
pedidos_sem_entrega["status_cancelado"] = status_cancelado.loc[data_vazia]

# Exibe os pedidos, seus status e a indicação de cancelamento.
display(
    pedidos_sem_entrega[
        ["pedido_id", "status_pedido", "data_entrega", "status_cancelado"]
    ]
)

      pedido_id status_pedido data_entrega  status_cancelado
0           844     Cancelado          NaN              True
8           186     Cancelado          NaN              True
21          662     Cancelado          NaN              True
49         1170     Concluído          NaN             False
59          896     Cancelado          NaN              True
...         ...           ...          ...               ...
1448       1260     Concluído          NaN             False
1453        298     Cancelado          NaN              True
1458        102     Cancelado          NaN              True
1480       1490     Cancelado          NaN              True
1487        282     Cancelado          NaN              True

[143 rows x 4 columns]

### 3.2) - Contar pedidos sem entrega e cancelados, e pedidos sem entrega com outro status.

In [74]:
# Seleciona os pedidos sem data de entrega cujo status é Cancelado.
pedidos_sem_entrega_cancelados = pedidos_sem_entrega.loc[
    pedidos_sem_entrega["status_cancelado"]
]

# Seleciona os pedidos sem data de entrega cujo status não é Cancelado.
pedidos_sem_entrega_outro_status = pedidos_sem_entrega.loc[
    ~pedidos_sem_entrega["status_cancelado"]
]

# Conta e exibe os pedidos de cada grupo.
print(
    "Pedidos sem entrega e cancelados:",
    len(pedidos_sem_entrega_cancelados)
)

print(
    "Pedidos sem entrega com outro status:",
    len(pedidos_sem_entrega_outro_status)
)

Pedidos sem entrega e cancelados: 109
Pedidos sem entrega com outro status: 34

### 3.3) - Mostra pelo menos 3 exemplos de ‘pedidos sem entrega e com outro status’.

In [75]:
# Informa que a tabela a seguir mostra exemplos de contraexemplos.
print("Exemplos de pedidos sem data de entrega com outro status:")

# Seleciona as colunas úteis para analisar os pedidos.
colunas_exibidas = [
    "pedido_id",
    "status_pedido",
    "data_entrega",
]

# Mostra até três registros do grupo com outro status.
display(
    pedidos_sem_entrega_outro_status[colunas_exibidas].head(3)
)

Exemplos de pedidos sem data de entrega com outro status:

     pedido_id status_pedido data_entrega
49        1170     Concluído          NaN
117        990     Concluído          NaN
152        740     Concluído          NaN

### 3.4) - Todo pedido sem entrega foi cancelado?

In [76]:
# Verifica se há pedidos sem data de entrega.
if pedidos_sem_entrega.empty:
    print("Não há pedidos sem data de entrega para verificar.")

# Se não há pedidos sem entrega com outro status, todos foram cancelados.
elif pedidos_sem_entrega_outro_status.empty:
    print("Sim: todos os pedidos sem data de entrega foram cancelados.")

# Se existe pelo menos um pedido com outro status, a hipótese é falsa.
else:
    print("Não: há pedidos sem data de entrega com outro status.")

Não: há pedidos sem data de entrega com outro status.

# 4 - Formatação Temporal (Datetime)

### 4.1 - Preservar o texto original: manter uma cópia do texto original da data.

In [83]:
# Cria uma cópia da coluna data_venda para preservar o texto original.
df["data_venda_original"] = df["data_venda"].copy()

# Exibe as duas colunas para conferir que o texto foi preservado.
display(df[["data_venda", "data_venda_original"]].head())

            data_venda  data_venda_original
0  2025-11-21 18:02:35  2025-11-21 18:02:35
1  2024-10-29 18:41:26  2024-10-29 18:41:26
2  2025-09-05 21:16:09  2025-09-05 21:16:09
3  2024-11-08 11:29:44  2024-11-08 11:29:44
4  2025-08-23 11:22:05  2025-08-23 11:22:05

### 4.2 - Preservar o texto original: Manter o registo original do texto.

In [86]:
from datetime import datetime

# Define o formato esperado: ano-mês-dia hora:minuto:segundo.
formato_origem = "%Y-%m-%d %H:%M:%S"

# Cria uma função para converter um valor de texto em data e hora.
def converter_data(texto):
    # Se o valor estiver ausente ou vazio, não tenta convertê-lo.
    if pd.isna(texto) or str(texto).strip() == "":
        return None

    try:
        # Interpreta o texto conforme o formato definido acima.
        return datetime.strptime(str(texto).strip(), formato_origem)
    except ValueError:
        # Se o texto não combinar com o formato, retorna None.
        return None

# Aplica a função a cada valor original e guarda os resultados numa nova coluna.
df["data_venda_convertida"] = df["data_venda_original"].map(converter_data)

### 4.3 - Extrair componentes da data: Isolar os campos de ano, mês, dia e hora.

In [84]:
# Garante que a coluna esteja no formato de data e hora do Pandas.
datas_convertidas = pd.to_datetime(
    df["data_venda_convertida"],
    errors="coerce"
)

# Extrai cada componente para uma coluna própria.
df["ano"] = datas_convertidas.dt.year
df["mes"] = datas_convertidas.dt.month
df["dia"] = datas_convertidas.dt.day
df["hora"] = datas_convertidas.dt.hour

# Exibe os valores para conferência.
display(
    df[
        [
            "data_venda_original",
            "data_venda_convertida",
            "ano",
            "mes",
            "dia",
            "hora",
        ]
    ].head()
)

   data_venda_original data_venda_convertida     ano   mes   dia  hora
0  2025-11-21 18:02:35   2025-11-21 18:02:35  2025.0  11.0  21.0  18.0
1  2024-10-29 18:41:26   2024-10-29 18:41:26  2024.0  10.0  29.0  18.0
2  2025-09-05 21:16:09   2025-09-05 21:16:09  2025.0   9.0   5.0  21.0
3  2024-11-08 11:29:44   2024-11-08 11:29:44  2024.0  11.0   8.0  11.0
4  2025-08-23 11:22:05   2025-08-23 11:22:05  2025.0   8.0  23.0  11.0

### 4.4 - Formatar para padrão brasileiro utilizando strftime(), com o formato "12/10/2025".

In [42]:
# Formata a data como dia/mês/ano.
df["data_venda_br"] = datas_convertidas.dt.strftime("%d/%m/%Y")

# Exibe o texto original e a data formatada para conferência.
display(
    df[
        [
            "data_venda_original",
            "data_venda_br",
        ]
    ].head()
)

   data_venda_original data_venda_br
0  2025-11-21 18:02:35    21/11/2025
1  2024-10-29 18:41:26    29/10/2024
2  2025-09-05 21:16:09    05/09/2025
3  2024-11-08 11:29:44    08/11/2024
4  2025-08-23 11:22:05    23/08/2025

### 4.5 - Contar e marcar datas vazias ou inválidas

In [43]:
# Prepara o texto original para verificar se está vazio.
texto_data = df["data_venda_original"].astype("string").str.strip()

# Marca datas ausentes ou que contêm apenas espaços.
data_vazia = (
    texto_data.isna()
    | texto_data.eq("").fillna(False)
)

# Marca datas preenchidas que não foram convertidas.
data_invalida = (
    ~data_vazia
    & df["data_venda_convertida"].isna()
)

# Registra as marcações em colunas novas.
df["data_venda_vazia"] = data_vazia
df["data_venda_invalida"] = data_invalida
df["data_venda_problematica"] = data_vazia | data_invalida

# Conta os casos encontrados.
total_vazias = int(data_vazia.sum())
total_invalidas = int(data_invalida.sum())
total_problematicas = int(df["data_venda_problematica"].sum())

print("Datas vazias:", total_vazias)
print("Datas inválidas:", total_invalidas)
print("Total de datas vazias ou inválidas:", total_problematicas)

Datas vazias: 0
Datas inválidas: 4
Total de datas vazias ou inválidas: 4

### 4.6 — Não preencher com a data atual

In [45]:
# Seleciona as linhas que foram marcadas como vazias ou inválidas no item 4.5.
linhas_com_problema = df["data_venda_problematica"]

# Conta quantas dessas linhas continuam sem uma data convertida.
total_sem_data = int(
    df.loc[linhas_com_problema, "data_venda_convertida"].isna().sum()
)

print("Registros problemáticos mantidos sem data:", total_sem_data)

# Exibe exemplos para conferir o texto original e o valor convertido.
display(
    df.loc[
        linhas_com_problema,
        ["data_venda_original", "data_venda_convertida"]
    ].head()
)

Registros problemáticos mantidos sem data: 4

    data_venda_original data_venda_convertida
152       data_invalida                   NaT
255       data_invalida                   NaT
714       data_invalida                   NaT
884       data_invalida                   NaT

# 5 - Relatório de Status Manual e Exploração

### 5.1 - Exibir um resumo

In [46]:
# Prepara os status para comparação, ignorando espaços e maiúsculas/minúsculas.
status = df["status_pedido"].astype("string").str.strip().str.casefold()

# Identifica pedidos sem data de entrega.
texto_entrega = df["data_entrega"].astype("string").str.strip()
sem_entrega = (
    df["data_entrega"].isna()
    | texto_entrega.eq("").fillna(False)
)

# Separa pedidos sem entrega entre cancelados e com outro status.
sem_entrega_cancelados = sem_entrega & status.eq("cancelado").fillna(False)
sem_entrega_outro_status = sem_entrega & ~status.eq("cancelado").fillna(False)

# Conta os pedidos cancelados, independentemente da data de entrega.
total_cancelados = int(status.eq("cancelado").fillna(False).sum())

# Monta uma tabela com os principais resultados.
resumo = pd.DataFrame({
    "Indicador": [
        "Total de linhas lidas",
        "Categorias vazias preenchidas",
        "Categorias não vazias alteradas",
        "Registros com problemas numéricos",
        "Datas de venda inválidas",
        "Pedidos cancelados",
        "Pedidos sem entrega e cancelados",
        "Pedidos sem entrega com outro status",
    ],
    "Quantidade": [
        len(df),
        vazias_preenchidas,
        nao_vazias_alteradas,
        int(df["tem_problema_numerico"].sum()),
        int(df["data_venda_invalida"].sum()),
        total_cancelados,
        int(sem_entrega_cancelados.sum()),
        int(sem_entrega_outro_status.sum()),
    ],
})

display(resumo)

                              Indicador  Quantidade
0                 Total de linhas lidas        1500
1         Categorias vazias preenchidas           0
2       Categorias não vazias alteradas           0
3     Registros com problemas numéricos          19
4              Datas de venda inválidas           4
5                    Pedidos cancelados         109
6      Pedidos sem entrega e cancelados         109
7  Pedidos sem entrega com outro status          34

### 5.2 - Contar pedidos por canal de venda

In [47]:
# Lista os canais que serão considerados reconhecidos.
canais_reconhecidos = ["Mercado", "Loja física", "Web"]

# Remove espaços das pontas antes de conferir cada canal.
canal_texto = df["canal_venda"].astype("string").str.strip()

# Marca os registros cujo canal está na lista de canais reconhecidos.
canal_reconhecido = canal_texto.isin(canais_reconhecidos)

# Conta pedidos por canal reconhecido e mostra também canais com zero pedidos.
contagem_por_canal = (
    canal_texto[canal_reconhecido]
    .value_counts()
    .reindex(canais_reconhecidos, fill_value=0)
    .rename_axis("Canal de venda")
    .reset_index(name="Total de pedidos")
)

# Conta e lista os registros excluídos por terem canal não reconhecido.
total_excluidos = int((~canal_reconhecido).sum())
canais_excluidos = canal_texto[~canal_reconhecido].fillna("<ausente>").unique()

print("Pedidos por canal reconhecido:")
display(contagem_por_canal)

print("Registros excluídos por canal não reconhecido:", total_excluidos)
print("Canais encontrados entre os registros excluídos:", canais_excluidos.tolist())

Pedidos por canal reconhecido:

  Canal de venda  Total de pedidos
0        Mercado               283
1    Loja física               551
2            Web               666

Registros excluídos por canal não reconhecido: 0
Canais encontrados entre os registros excluídos: []

### 5.3 - Contar pedidos por ano e mês

In [48]:
# Garante que os valores estejam no formato de data do Pandas.
datas_venda = pd.to_datetime(
    df["data_venda_convertida"],
    errors="coerce"
)

# Marca quais registros têm uma data válida.
data_valida = datas_venda.notna()

# Separa o ano e o mês como um único período, por exemplo: 2024-10.
ano_mes = datas_venda[data_valida].dt.to_period("M")

# Conta os pedidos em cada período e organiza do mais antigo ao mais recente.
contagem_por_periodo = (
    ano_mes.value_counts()
    .sort_index()
    .rename_axis("Ano e mês")
    .reset_index(name="Total de pedidos")
)

# Conta os registros excluídos por não terem data válida.
total_excluidos = int((~data_valida).sum())

print("Pedidos registrados por ano e mês:")
display(contagem_por_periodo)

print("Registros excluídos por data de venda ausente ou inválida:", total_excluidos)

Pedidos registrados por ano e mês:

  Ano e mês  Total de pedidos
0   2024-08                77
1   2024-09               104
2   2024-10               393
3   2024-11               174
4   2025-08                62
5   2025-09                94
6   2025-10               410
7   2025-11               182

Registros excluídos por data de venda ausente ou inválida: 4

### 5.4 - Nas contagens por canal e por período

In [49]:
# Conta os status nos registros com canal reconhecido.
# dropna=False inclui também pedidos cujo status esteja vazio.
status_por_canal = (
    df.loc[canal_reconhecido, "status_pedido"]
    .value_counts(dropna=False)
    .rename_axis("Status")
    .reset_index(name="Total de pedidos")
)

# Conta os status nos registros com data de venda válida.
status_por_periodo = (
    df.loc[data_valida, "status_pedido"]
    .value_counts(dropna=False)
    .rename_axis("Status")
    .reset_index(name="Total de pedidos")
)

# Conta quantos registros entraram e quantos foram excluídos em cada análise.
incluidos_canal = int(canal_reconhecido.sum())
excluidos_canal = int((~canal_reconhecido).sum())

incluidos_periodo = int(data_valida.sum())
excluidos_periodo = int((~data_valida).sum())

print("Por canal — todos os status nos registros com canal reconhecido:")
display(status_por_canal)
print("Registros incluídos:", incluidos_canal)
print("Registros excluídos por canal não reconhecido:", excluidos_canal)

print("\nPor período — todos os status nos registros com data válida:")
display(status_por_periodo)
print("Registros incluídos:", incluidos_periodo)
print("Registros excluídos por data ausente ou inválida:", excluidos_periodo)

Por canal — todos os status nos registros com canal reconhecido:

      Status  Total de pedidos
0  Concluído              1345
1  Cancelado               109
2  Devolvido                46

Registros incluídos: 1500
Registros excluídos por canal não reconhecido: 0

Por período — todos os status nos registros com data válida:

      Status  Total de pedidos
0  Concluído              1341
1  Cancelado               109
2  Devolvido                46

Registros incluídos: 1496
Registros excluídos por data ausente ou inválida: 4

### 5.5 - Apresentar duas descobertas

In [50]:
# Descoberta por canal: encontra o canal com mais pedidos.
indice_maior_canal = contagem_por_canal["Total de pedidos"].idxmax()
maior_canal = contagem_por_canal.loc[indice_maior_canal]

total_canais_contados = contagem_por_canal["Total de pedidos"].sum()

if total_canais_contados > 0:
    percentual_maior_canal = (
        maior_canal["Total de pedidos"] / total_canais_contados
    ) * 100

    print(
        f"Descoberta por canal: {maior_canal['Canal de venda']} "
        f"teve mais pedidos, com {maior_canal['Total de pedidos']} "
        f"de {total_canais_contados} pedidos contados "
        f"({percentual_maior_canal:.1f}%)."
    )
    print(
        "Interpretação: esse foi o canal com maior número de pedidos "
        "registrados entre os canais reconhecidos."
    )
    print(
        "Limitação: a contagem inclui todos os status e não representa "
        "receita nem somente vendas concluídas; canais não reconhecidos "
        "foram excluídos."
    )
else:
    print("Descoberta por canal: não há pedidos com canal reconhecido para comparar.")


# Descoberta por período: encontra o ano e mês com mais pedidos.
if not contagem_por_periodo.empty:
    indice_maior_periodo = contagem_por_periodo["Total de pedidos"].idxmax()
    maior_periodo = contagem_por_periodo.loc[indice_maior_periodo]

    total_periodos_contados = contagem_por_periodo["Total de pedidos"].sum()
    percentual_maior_periodo = (
        maior_periodo["Total de pedidos"] / total_periodos_contados
    ) * 100

    print(
        f"\nDescoberta por período: {maior_periodo['Ano e mês']} "
        f"teve mais pedidos, com {maior_periodo['Total de pedidos']} "
        f"de {total_periodos_contados} pedidos contados "
        f"({percentual_maior_periodo:.1f}%)."
    )
    print(
        "Interpretação: esse foi o período com maior número de pedidos "
        "registrados entre os que tinham data de venda válida."
    )
    print(
        "Limitação: a contagem inclui todos os status e não representa "
        "receita nem somente vendas concluídas; datas ausentes ou inválidas "
        "foram excluídas."
    )
else:
    print("\nDescoberta por período: não há datas válidas para comparar.")

Descoberta por canal: Web teve mais pedidos, com 666 de 1500 pedidos contados (44.4%).
Interpretação: esse foi o canal com maior número de pedidos registrados entre os canais reconhecidos.
Limitação: a contagem inclui todos os status e não representa receita nem somente vendas concluídas; canais não reconhecidos foram excluídos.

Descoberta por período: 2025-10 teve mais pedidos, com 410 de 1496 pedidos contados (27.4%).
Interpretação: esse foi o período com maior número de pedidos registrados entre os que tinham data de venda válida.
Limitação: a contagem inclui todos os status e não representa receita nem somente vendas concluídas; datas ausentes ou inválidas foram excluídas.

### 5.6 - Esclarecer o que as contagens representam

In [51]:
print(
    "Observação: as contagens por canal e por período representam "
    "pedidos registrados na base de dados. Elas incluem todos os status "
    "e não representam valores de receita nem somente vendas concluídas."
)

Observação: as contagens por canal e por período representam pedidos registrados na base de dados. Elas incluem todos os status e não representam valores de receita nem somente vendas concluídas.

# 6 - Relatório e insights

### 6.1 - Exibir um resumo com o total de linhas

### 6.2 - Incluir no resumo dois grupos sem data de entrega

### 6.3 - Contar pedidos por canal de venda

### 6.4 - Contar pedidos por ano e mês

### 6.5 - Nas contagens por canal e por período

### 6.6 - Apresentar duas descobertas

### 6.7 - O que se pode afirmar sobre análise